# Generated by Django 4.1.3 on 2022-11-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_vechicle_total_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechicle',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
