# Generated by Django 4.1.3 on 2022-11-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_user_vechicle_vechicle_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='user_activity',
            new_name='user',
        ),
    ]
