# Generated by Django 4.1.3 on 2022-11-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rename_vechicle_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='type',
        ),
    ]
